export const BEGIN_FETCH_DATA = "BEGIN_FETCH_DATA";
export const SUCCESS_FETCH_DATA = "SUCCESS_FETCH_DATA";
export const ERROR_FETCH_DATA = "ERROR_FETCH_DATA";
export const ACTION_CHANGE_REMEMBER = "ACTION_CHANGE_REMEMBER";
export const ACTION_CHANGE_LOGIN_INFO = "ACTION_CHANGE_LOGIN_INFO";
export const ACTION_BEGIN_LOGIN = "ACTION_LOGIN";
export const ACTION_CHANGE_SESSION = "ACTION_SUCCESS_LOGIN";
export const ACTION_ERROR_LOGIN = "ACTION_FAILED_LOGIN";

